webos-compat.inc: add python3-protobuf to ROS_WORLD_SKIP_GROUPS
* there are more recipes depending on blacklisted python3-protobuf in Noetic
* fixes:
ERROR: Nothing PROVIDES 'python3-grpcio-tools' (but /jenkins/mjansa/build/ros/webos-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/fkie-multimaster/fkie-multimaster-msgs_1.2.3-1.bb DEPENDS on or otherwise requires it)
python3-grpcio-tools was skipped: Recipe is blacklisted: Depends on blacklisted python3-protobuf which is not compatible with old protobuf from meta-webos/recipes-devtools/protobuf/protobuf_3.6.1.bb
NOTE: Runtime target 'fkie-node-manager-daemon' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fkie-node-manager-daemon', 'fkie-multimaster-msgs', 'python3-grpcio-tools']
NOTE: Runtime target 'fkie-master-discovery' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fkie-master-discovery', 'fkie-multimaster-msgs', 'python3-grpcio-tools']
NOTE: Runtime target 'fkie-master-sync' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fkie-master-sync', 'fkie-master-discovery', 'fkie-multimaster-msgs', 'python3-grpcio-tools']
NOTE: Runtime target 'fkie-multimaster-msgs' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fkie-multimaster-msgs', 'python3-grpcio-tools']
ERROR: Nothing PROVIDES 'fkie-master-discovery' (but /jenkins/mjansa/build/ros/webos-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/fkie-multimaster/fkie-master-sync_1.2.3-1.bb DEPENDS on or otherwise requires it)
No eligible PROVIDERs exist for 'fkie-master-discovery'
ERROR: Nothing RPROVIDES 'python3-grpcio' (but /jenkins/mjansa/build/ros/webos-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/fkie-multimaster/fkie-node-manager-daemon_1.2.3-1.bb RDEPENDS on or otherwise requires it)
python3-grpcio was skipped: Recipe is blacklisted: Depends on blacklisted python3-protobuf which is not compatible with old protobuf from meta-webos/recipes-devtools/protobuf/protobuf_3.6.1.bb
NOTE: Runtime target 'python3-grpcio' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-grpcio']
ERROR: Nothing RPROVIDES 'fkie-node-manager-daemon-dev' (but /jenkins/mjansa/build/ros/webos-noetic-hardknott/meta-ros/meta-ros1-noetic/generated-recipes/fkie-multimaster/fkie-node-manager-daemon_1.2.3-1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'fkie-node-manager-daemon-dev'
NOTE: Runtime target 'fkie-node-manager-daemon-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['fkie-node-manager-daemon-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>